@extends('../includes.layout')
@section('meta_tag')
	<title>Sole Proprietorship Business Registration in Lahore</title>
@endsection
@section('main_content')
<div class="rs-project-details pt-100 md-pt-80">
    <div class="container">
    	<div class="row">
    		<div class="col-lg-8 md-mb-50 pr-20 md-pr-15">
    			<div class="sec-title2 mb-45">
					<div class="project-title">
						<h3 class="title pb-35">Sole Proprietorship Business Registration in Lahore</h3>
					</div>
					<div class="desc pb-30">
						A sole proprietorship is a simple and most common lawful arrangement that somebody may select. It's a distinct business owned and running by one individual wherein there is no difference in between the owner and its business.
					</div>
					<div class="desc pb-30">
						Before going into detailed discussion about registration process of sole proprietorship it is important to apprehend the concept of sole proprietorship business 
					</div>
				</div>
    		</div>
    		<div class="col-lg-4 pl-40 md-pl-15">
    			<div class="project-information">
    				<div class="project-title">
    					<h3 class="title pb-35">Service Info</h3>
    				</div>
    				<div class="project-content mb-22">
    					<h4 class="title">Skills</h4>
    					<div class="description">
    					    Buffing, Mopping, Dusting            		
    					</div>
    				</div>
    				<div class="project-content mb-22">
    					<h4 class="title">Client</h4>
    					<div class="description">
    					    John Dibag           		
    					</div>
    				</div>
    			</div>
    		</div>
    	</div>
    </div>
</div>
<div class="rs-services services-style1">
    <div class="container">
    	<div class="sec-title2">
			<div class="row">
	    		<div class="col-lg-12 ">
	    			<div>
	    				<h3 class="title">What is sole proprietorship?</h3>
	    			</div>
	    			<div class="desc mb-20">
	    				Sole proprietorship business can be defined as;
	    				<p class="px-5">
	    					<b>A sole proprietorship also denoted as a sole trader or a proprietorship, is an standalone business that has just single owner who is required to pay income tax personally on profits generated by the business</b>
	    				</p>
	    			</div>
	    			<div class="desc mb-20">
	    				It normally occurs when you have qualities of a leader, and cannot work under the people as it makes you tired, and somewhat pushes you to start your own business set up.
	    			</div>
	    			<div class="desc mb-20">
	    				Sole Proprietorship Business gives an opportunity to feel and be yourself a leader.
	    			</div>
	    			<div class="desc mb-20">
	    				Proprietorship is the most famous category of business structure lead by businessmen in Lahore as well as other cities of Pakistan. This category of business structure looks usually around like
	    				<ul class="check-lists px-5">
	    					<li>Saloons, </li>
	    					<li>Photographers, </li>
	    					<li>General Stores,</li>
	    					<li>The chemist, </li>
	    					<li>Motor Mechanics,</li>
	    					<li>Doctors </li>
	    					<li>Grocery shops,</li>
	    					<li>Lawyers/Advocates are the simple examples of sole proprietors.</li>
	    				</ul>
	    			</div>
	    			<div>
	    				<h3 class="title">Why to Register Your Business as Sole Proprietor in Pakistan?</h3>
	    			</div>
	    			<div class="desc mb-20">
    					The registration of a sole proprietorship structure of business is quite easy as in comparison with any other form of business like partnership firm registration or private limited company registration. One of the main cause for easily managing of sole proprietor business is that it is handled by a single person but it does not reveal any restriction for employment and sole proprietor can easily employ the required number of employees to manage and run his business effectively.
    				</div>
    				<div class="desc mb-20">
    					The sole proprietor has an option to use any name for business but depends on the name cited in the sole proprietor certificate of registration issued by the Federal Board of Revenue. Sole proprietor is also permitted to open the Bank Account with his business name.
    				</div>
    				<div class="desc mb-20">
    					Let’s move towards the main features of Sole Proprietorship Business in Pakistan;
    				</div>
    				<div>
    					<h3 class="title">Features of Sole Proprietorship</h3>
    				</div>
					<div class="desc mb-20">
	    				Overview of features of Sole Proprietorship is as under;
	    			</div>
	    		</div>
	    	</div>
	    	<div class="row mb-5">
	    		<div class="col-lg-4 col-md-6 mb-20">
	    			<div class="services-item">
	    				<div class="services-wrap">
	    					<div class="serial-number">
	    						01
	    					</div>
	    					<div class="services-icon">
	    						<img src="assets/images/services/style1/1.png" alt="Services">
	    					</div>
	    					<div class="services-content">
	    						<h3 class="title">No Separate Identity</h3>
	    					</div>
	    				</div>
	    			</div>
	    		</div>
	    		<div class="col-lg-4 col-md-6 mb-20">
	    			<div class="services-item">
	    				<div class="services-wrap">
	    					<div class="serial-number">
	    						02
	    					</div>
	    					<div class="services-icon">
	    						<img src="assets/images/services/style1/2.png" alt="Services">
	    					</div>
	    					<div class="services-content">
	    						<h3 class="title">Unlimited Liabilities</h3>
	    					</div>
	    				</div>
	    			</div>
	    		</div>
	    		<div class="col-lg-4 col-md-6 mb-20">
	    			<div class="services-item">
	    				<div class="services-wrap">
	    					<div class="serial-number">
	    						03
	    					</div>
	    					<div class="services-icon">
	    						<img src="assets/images/services/style1/3.png" alt="Services">
	    					</div>
	    					<div class="services-content">
	    						<h3 class="title">Lack of legal formalities</h3>
	    					</div>
	    				</div>
	    			</div>
	    		</div>
	    		<div class="col-lg-4 col-md-6 mb-20 offset-lg-2">
	    			<div class="services-item">
	    				<div class="services-wrap">
	    					<div class="serial-number">
	    						04
	    					</div>
	    					<div class="services-icon">
	    						<img src="assets/images/services/style1/4.png" alt="Services">
	    					</div>
	    					<div class="services-content">
	    						<h3 class="title">Community of Business</h3>
	    					</div>
	    				</div>
	    			</div>
	    		</div>
	    		<div class="col-lg-4 col-md-6 mb-20 offset-md-3 offset-lg-0">
	    			<div class="services-item">
	    				<div class="services-wrap">
	    					<div class="serial-number">
	    						05
	    					</div>
	    					<div class="services-icon">
	    						<img src="assets/images/services/style1/5.png" alt="Services">
	    					</div>
	    					<div class="services-content">
	    						<h3 class="title">No profile or loss sharing</h3>
	    					</div>
	    				</div>
	    			</div>
	    		</div>
	    	</div>
	    	<div class="row">
	    		<div class="col-lg-12">
	    			<div>
	    				<h3 class="title">Explanation of features of Sole Proprietorship is discussed as under</h3>
	    			</div>
	    		</div>
	    	</div>
	    	<div class="row my-3">
    			<div class="col-lg-12 col-md-12 mb-20">
	    			<div class="services-item">
	    				<div class="services-wrap">
	    					<div class="services-content pt-0">
	    						<h3 class="title">No separate legal entity</h3>
	    						<p class="services-txt">
	    							Business and owner of the business are one and the same. No separate legal identity will be bestowed upon the sole proprietorship. So, the owner is responsible for all the activities and business transactions.
	    						</p>
	    					</div>
	    				</div>
	    			</div>
	    		</div>
	    		<div class="col-lg-12 col-md-12 mb-20">
	    			<div class="services-item">
	    				<div class="services-wrap">
	    					<div class="services-content pt-0">
	    						<h3 class="title">Unlimited Liabilities</h3>
	    						<p class="services-txt">
	    							Owner and the business are not separate from each other, and also the owner has limited liability.
	    						</p>
	    					</div>
	    				</div>
	    			</div>
	    		</div>
	    		<div class="col-lg-12 col-md-12 mb-20">
	    			<div class="services-item">
	    				<div class="services-wrap">
	    					<div class="services-content pt-0">
	    						<h3 class="title">Lack of legal formalities</h3>
	    						<p class="services-txt">
	    							A sole proprietorship has no any distinct law to manage it. There is no need for incorporation or registration certificate of any type. Mostly, a license only is needed to start the proprietorship business.
	    						</p>
	    					</div>
	    				</div>
	    			</div>
	    		</div>
	    		<div class="col-lg-12 col-md-12 mb-20">
	    			<div class="services-item">
	    				<div class="services-wrap">
	    					<div class="services-content pt-0">
	    						<h3 class="title">Continuity of business</h3>
	    						<p class="services-txt">
	    							It is totally reliant on its owner. The death, retirement, bankruptcy, insanity and imprisonment have effect on sole proprietorship. In mostly cases, the business comes to an end the proprietorship ceases to exist.
	    						</p>
	    					</div>
	    				</div>
	    			</div>
	    		</div>
	    		<div class="col-lg-12 col-md-12 mb-20">
	    			<div class="services-item">
	    				<div class="services-wrap">
	    					<div class="services-content pt-0">
	    						<h3 class="title">No profit and loss sharing</h3>
	    						<p class="services-txt">
	    							There is only the owner who is risk bearer in a sole proprietorship. As he is the only investor in the company, therefore, he has to bear all the risks.
	    						</p>
	    					</div>
	    				</div>
	    			</div>
	    		</div>
	    	</div>
	    	<div class="row">
	    		<div class="col-lg-12">
	    			<div class="desc mb-20">
	    				Let’s move towards the process of registration of sole proprietorship in Lahore, Pakistan
	    			</div>
	    			<div>
	    				<h3 class="title">Registration of a Sole Proprietorship Business in Lahore, Pakistan</h3>
	    			</div>
	    			<div class="desc mb-20">
	    				Mostly Businessmen find it appropriate to select proprietorship business because of its natural creation and compliance with Govt Departments. All the concern of Profit and loss of proprietorship business goes to the Owner.
	    			</div>
	    			<div>
	    				<h6 class="title">In order to register your business as Sole Proprietorship all you need to do is:</h6>
	    			</div>
	    			<div class="desc mb-20">
	    				<ul class="check-lists px-5">
							<li>Selecting a name for the business/ Sole Proprietorship.</li>
							<li>For application for Registration of Sole Proprietorship, you must have a National Tax Number (NTN) issued by the FBR. You will be provided an NTN certificate with your name & details on it.</li>
							<li>Make letterhead and business card for your Sole proprietorship business including name, phone number, logo, and address of your physical business office.</li>
							<li>Furnish a request on the letterhead duly signed and stamped along with your CNIC and business card with any bank in order to open a business account for the Sole proprietorship Business.</li>
							<li>When your account will be opened, you would be provided a maintenance certificate from the bank.</li>
							<li>After opening an account, you can also apply for Sales Tax (GST) registration.</li>
	    				</ul>
	    			</div>
	    			<div>
	    				<h3 class="title">Who is required to register for sales tax in Pakistan?Step wise Registration procedure is discussed under</h3>
	    			</div>
	    			<div class="desc mb-20">
	    				Registration process of Sole Proprietorship Business in Lahore is an online which is discussed below in detail;
	    			</div>
	    			<div>
	    				<h3 class="title">Steps for registration</h3>
	    			</div>
	    			<div class="desc mb-20">
	    				Steps involved in registration of sole proprietorship are listed below;
	    			</div>
	    			<div>
	    				<h5 class="title">Step-1; Filling of documents</h5>
	    			</div>
	    			<div class="desc mb-20">
	    				Following are the required documents and method under which registration made in Pakistan;
	    			</div>
	    			<div>
	    				<h6 class="title">Documents needed for Registration of Sole Proprietorship Business in Lahore, Pakistan</h6>
	    			</div>
	    			<div class="desc mb-20">
	    				The following are the documents needed for Registration of Sole Proprietorship Business
	    				<ol class="order-list px-5">
							<li>Copy of National Identity Card issued by the Nadra.</li>
							<li>Mobile number along with Email Address of Sole Proprietor that is not ever registered with the FBR.</li>
							<li>Business Name, Address and Principle operation of the Business. </li>
							<li>Paid Electricity Bill of the last three months</li>
							<li>Rent agreement of Business Premises along with CNIC Copy of Premises Owner</li>
	    				</ol>
	    			</div>
	    			<div>
	    				<h5 class="title">Step-2; Opening of bank account</h5>
	    			</div>
	    			<div class="desc mb-20">
	    				Procedure for registration of Sole Proprietorship following opening of bank account is discussed as under;
	    				<ul class="check-lists px-5">
							<li>Create your ‘FBR Login through IRIS’</li>
							<li>Fill out Form 181 for enrollment in FBR System.</li>
							<li>Add your Business and Address and choose Business Principle Activity</li>
							<li>Attach Requisite documents with Form 181 and Submit for issuance of NTN  </li>
							<li>After creating NTN proceed for opening Business Bank Account in any commercial Bank and start your business.</li>	    					
	    				</ul>
	    			</div>
	    			<div>
	    				<h3 class="title">Transfer of Registration</h3>
	    			</div>
	    		</div>
	    	</div>
		</div>
    </div>
</div>
<div class="rs-faq faq-style1 pb-80 md-pb-80">
	<div class="container">
		<div class="row">
			<div class="col-md-8 pr-55 md-pr-15 md-mb-50">
				<div class="faq-content">
                   <div id="accordion" class="accordion">
                      <div class="card">
                          <div class="card-header">
                              <a class="card-link" href="#" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true">FBR Login</a>
                          </div>
                          <div id="collapseOne" class="collapse show" data-bs-parent="#accordion">
                              <div class="card-body">
                                   Create FBR login on IRIS by the enrollment process.
                              </div>
                          </div>
                      </div>
                       <div class="card">
                           <div class="card-header">
                               <a class="card-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false">Form 181</a>
                           </div>
                           <div id="collapseTwo" class="collapse" data-bs-parent="#accordion" style="">
                               <div class="card-body">
                                    Sign in and fill out Form 181 for enrollment in FBR system.
                               </div>
                           </div>
                       </div>
                       <div class="card">
                           <div class="card-header">
                               <a class="card-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false">Add your Business</a>
                           </div>
                           <div id="collapseThree" class="collapse" data-bs-parent="#accordion" style="">
                               <div class="card-body">
                                   Add your business along with address and choose the principle activity of your business.
                               </div>
                           </div>
                       </div>
                       <div class="card">
                           <div class="card-header">
                               <a class="card-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false">Submit form 181</a>
                           </div>
                           <div id="collapseFour" class="collapse" data-bs-parent="#accordion" style="">
                               <div class="card-body">
                                   Attach requisite documents and submit form 181 for issuance of NTN.
                               </div>
                           </div>
                       </div>
                       <div class="card">
                           <div class="card-header">
                               <a class="card-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseFive" aria-expanded="false">Open bank account</a>
                           </div>
                           <div id="collapseFive" class="collapse" data-bs-parent="#accordion" style="">
                               <div class="card-body">
                                   After issuance of the NTN proceed for the opening of bank account and commence your business.
                               </div>
                           </div>
                       </div>
                   </div>
                </div>
			</div>
		</div>
	</div>
</div>
<div class="rs-services services-style1 pb-80 md-pb-80">
    <div class="container">
    	<div class="sec-title2">
			<div class="row">
	    		<div class="col-lg-12 ">
	    			<div>
	    				<h3 class="title">Benefits available to a Sole Proprietorship Business in Lahore, Pakistan</h3>
	    			</div>
	    			<div class="desc mb-20">
	    				Some of the benefits to register your business as Sole Proprietorship business are discussed below;
	    			</div>
	    			<div class="desc mb-20">
	    				A sole proprietor is the most popular business structures in Lahore as well as other cities in Pakistan to select for new arrangement for individuals who wish to arrange and manage everything on their own.
	    			</div>
	    			<div class="desc mb-20">
	    				There are the following benefits available to this type of business structure:
	    				<ul class="check-lists px-5">
	    					<li>Having flexibility in managing operations of business.</li>
							<li>It is one of the historic and most manageable business structures</li>
							<li>There is no complex structure of management.</li>
							<li>Easily starting and closing the business</li>
							<li>There are only fewer departmental compliance in this category of business</li>
							<li>There is a sense of Self- Responsibility in it.</li>
							<li>You are only boss in this business</li>
							<li>There is no need to share Income and Profit with anyone else.</li>
							<li>There are no chances of disputes with Partners or members like in other business structures or companies.</li>
	    				</ul>
	    			</div>
	    			<div>
	    				<h3 class="title">Post Compliance of Sole Proprietorship business</h3>
	    			</div>
	    			<div class="desc mb-20">
    					Here are some of the post compliances of Sole proprietorship;
    					<ol>
    						<li>The Proprietor is liable to file his annual Income Tax Returns timely in the Federal Board of Revenue.</li>
    						<li>The Proprietor is also required to file his monthly Sales Tax Return in case if he is also registered in Sales Tax with FBR or PRA respectively.</li>
    					</ol>
    				</div>
	    		</div>
	    	</div>
		</div>
    </div>
</div>
@endsection